---
name: Release created
defaults:
  run:
    shell: bash
concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: false
on:
  release:
    types:
      - created
jobs:
  released:
    uses: kare/github/.github/workflows/go-release.yaml@v0.5.0
    inputs:
      go_module_path: kkn.fi/rot13
      version: ${{ github.event.release.tag_name }}
